/**
 * CDN TTS provider — serves pre-generated audio files from a CDN or local public/ dir.
 *
 * Looks up text in the audio manifest (generated by scripts/generate-audio.mjs)
 * and fetches the corresponding MP3 file. Zero-config for end users.
 */

// The manifest is generated at build time and maps "langId:text" → { filename, voice, rate }
import audioManifest from '../../data/audioManifest.json';

const CDN_BASE = import.meta.env.VITE_CDN_BASE_URL || '/audio';

const cdnProvider = {
  id: 'cdn',
  label: 'Pre-recorded (CDN)',

  isConfigured() {
    // Always available — no credentials needed
    return true;
  },

  getConfig() {
    return { cdnBase: CDN_BASE };
  },

  saveConfig() {
    // No-op — nothing to configure
  },

  configFields: [],

  async speak(text, { ssmlLang = 'ko-KR' } = {}) {
    // Resolve languageId from ssmlLang (e.g. "ko-KR" → "ko", "es-ES" → "es")
    const langId = ssmlLang.split('-')[0];
    const manifestKey = `${langId}:${text}`;
    const entry = audioManifest[manifestKey];

    if (!entry) {
      throw new Error(`CDN audio not found for [${langId}]: "${text.slice(0, 50)}..."`);
    }

    const url = `${CDN_BASE}/${entry.filename}`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`CDN fetch failed (${response.status}): ${url}`);
    }

    const audioBlob = await response.blob();
    return URL.createObjectURL(audioBlob);
  },
};

export default cdnProvider;
